# Generated by Django 4.2.4 on 2023-09-09 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/",
                validators=[django.core.validators.FileExtensionValidator(["py"])],
            ),
        ),
    ]
