version: '3.8'

services:
  web:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./src/.env
    volumes:
      - ./src:/usr/src/app/
    ports:
      - 1337:8000
    depends_on:
      - redis
      - db
  db:
    image: postgres:13
    env_file: ./src/.env
    ports:
     - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine

  celery:
    build: ./src
    command: celery --app=django_project worker --loglevel=info --logfile=logs/celery.log
    env_file: ./src/.env
    volumes:
      - ./src:/usr/src/app
      - ./tmp/messages:/tmp/messages
    depends_on:
      - web
      - redis

  celery-beat:
      build: ./src
      command: celery -A django_project beat -l info
      env_file: ./src/.env
      volumes:
        - ./src:/usr/src/app
      depends_on:
        - redis

  dashboard:
    build: ./src
    command: celery flower -A django_project --port=5555 --broker=redis://redis:6379/0
    env_file: ./src/.env
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery

volumes:
  postgres_data:
